### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by joeinnes** [inetis-ch/oc-ListSwitch#8]
Hi,

I added a custom boolean column to my list by extending the Users controller, and would like to use this plugin to toggle quickly various properties.

When I use the 'switch' type, it works fine, but when I set the column type to `inetis-list-switch`, I get an 'undefined index' error here:

````php
private function getConfig($config = null)
{
    if (is_null($config)) {
        // this line generates the error
        return self::$listConfig[$this->name];
    }
  
    return self::$listConfig[$this->name][$config];
}
````

It seems that the $listConfig array is not properly populated, but I'm not sure why. 

Any ideas?

**Comment by Fl0Cri** [comment]
Hi, this error is now fixed in 1.1.0.

I suppose you were using something like this in the `boot` method of your plugin.
```php
Users::extendListColumns(function(Lists $widget) {
    $widget->addColumns(['is_guest' => [
        'type' => 'inetis-list-switch',
    ]]);
});
```

Note that if ListSwitch cannot add it automatically (du to plugins load order), you may need to add a `'clickable' => false,` option. Otherwise, clicking the column will trigger a navigation instead of switching the value.
