### ISSUE TITLE
crashes tailor plugins in October 3

### ISSUE THREAD

**Issue by Pixinside** [inetis-ch/oc-ListSwitch#9]
Tailor plugins don't work when listswitch is installed:

```
Undefined property: stdClass::$columns
~/plugins/inetis/listswitch/Plugin.php line 50
```

**Comment by mlieshout** [comment]
+1

**Comment by Fl0Cri** [comment]
Fixed by https://github.com/inetis-ch/oc-ListSwitch-plugin/commit/6d1c0a96fcefebdea03f48b9f77d874665c61509 in the new 1.1.0 release.

This doesn't introduce support for ListSwitch in Tailor, but at least it should not crash anymore.

Note that full Tailor support seems complicated as we only write form fields, and the list is built automatically from them using some kind of mapping (i.e. `checkbox` becomes `switch`). If there is interest in an actual Tailor support, feel free to open a dedicated issue or send a pull request.
